name: announce
on: push
jobs:
  new_composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/announce
        with:
          app-name: pixelpost
