name: context
on: push
jobs: 
 context:
   runs-on: ubuntu-latest
   steps: 
    - name: context push
      run: | 
          echo "Repository: ${{github.repository}}"
          echo "Branch: ${{github.ref_name}}"
          echo "commit: ${{github.sha}}"
          echo "Event: ${{github.event_name}}"
          echo "Runner OS: ${{runner.os}}"

