name: secret-check
on: push
jobs: 
 secrete:
   runs-on: ubuntu-latest
   steps: 
     - name: secrete workflow
       env: 
         APP_TOKEN: ${{secrets.APP_TOKEN}} 
       run: |
         if [ -n "$APP_TOKEN" ]; then
           echo "APP_TOKEN is available to this step"
         else 
           echo "APP_TOKEN is missing"
           exit 1
         fi



